const meta = require("./Assets/brand-icons/meta.png");
const starry = require("./Assets/icons/starry.png");
const linkedIn = require("../components/Assets/brand-icons/linkedin.png");


const jobArray = [
  {
    id: "3B",
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "/meta",
  },
  {
    id: "3a",
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link:"/loom",
  },
  {
    id: "4a",
    img: linkedIn,
    post: "Data Analytics",
    company: "LinkedIn Corporation",
    location: "Australia",
    type: "Full-time",
    pay: "105k-130k",
    timePosted: "posted 1hour ago",
    link:"/linkedIn",
  },
  {
    id: "5c",
    img: "https://cdn-icons-png.flaticon.com/512/174/174848.png",
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 2hours ago",
    link:"/facebook",
  },
  {
    id: "2F",
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "/meta",
  },
  {
    id: "2E",
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link:"/loom",
  },
  {
    id: "11a",
    img: linkedIn,
    post: "Data Analytics",
    company: "LinkedIn Corporation",
    location: "Australia",
    type: "Full-time",
    pay: "105k-130k",
    timePosted: "posted 45mins ago",
    link:"/linkedIn",
  },
  {
    id: "10b",
    img: "https://cdn-icons-png.flaticon.com/512/174/174848.png",
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 35mins ago",
    link:"/facebook",
  },
  {
    id: "2a",
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "/meta",
  },
  {
    id: "2b",
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link:"/loom",
  },
  {
    id: "30a",
    img:  linkedIn,
    post: "Data Analytics",
    company: "LinkedIn Corporation",
    location: "Australia",
    type: "Full-time",
    pay: "105k-130k",
    timePosted: "posted 35mins ago",
    link:"/linkedIn",
  },
  {
    id: "1b",
    img: "https://cdn-icons-png.flaticon.com/512/174/174848.png",
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 35mins ago",
    link:"/facebook",
  },
  {
    id: "2D",
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "/meta",
  },
  {
    id: "2C",
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link:"/loom",
  },
  {
    id: "1x",
    img: linkedIn,
    post: "Data Analytics",
    company: "LinkedIn Corporation",
    location: "Australia",
    type: "Full-time",
    pay: "105k-130k",
    timePosted: "posted 35mins ago",
    link:"/linkedIn",
  },
  {
    id: "1z",
    img: "https://cdn-icons-png.flaticon.com/512/174/174848.png",
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 35mins ago",
    link:"/facebook",
  },
];

export default jobArray;
