const meta = require("./Assets/brand-icons/meta.png");
const linkedin = require("./Assets/brand-icons/linkedin.png");
const starry = require("./Assets/icons/starry.png");

const jobArray = [
  {
    key: Math.random().toString(),
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "https://www.metacareers.com/facebook-life/remote/?p[offices][0]=Remote%2C%20Canada&p[offices][1]=Remote%2C%20France&p[offices][2]=Remote%2C%20Germany&p[offices][3]=Remote%2C%20Ireland&p[offices][4]=Remote%2C%20Italy&p[offices][5]=Remote%2C%20Netherlands&p[offices][6]=Remote%2C%20Poland&p[offices][7]=Remote%2C%20Spain&p[offices][8]=Remote%2C%20Sweden&p[offices][9]=Remote%2C%20UK&p[offices][10]=Remote%2C%20US&offices[0]=Remote%2C%20Canada&offices[1]=Remote%2C%20France&offices[2]=Remote%2C%20Germany&offices[3]=Remote%2C%20Ireland&offices[4]=Remote%2C%20Italy&offices[5]=Remote%2C%20Netherlands&offices[6]=Remote%2C%20Poland&offices[7]=Remote%2C%20Spain&offices[8]=Remote%2C%20Sweden&offices[9]=Remote%2C%20UK&offices[10]=Remote%2C%20US&no_rdr=0",
  },
  {
    key: Math.random().toString(),
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link: "https://boards.greenhouse.io/loominc/jobs/4010970005",
  },
  {
    key: "1a",
    img: linkedin,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "105k-130k",
    timePosted: "posted 35mins ago",
    link: "https://boards.greenhouse.io/loominc/jobs/4010970005",
  },
  {
    key: "1b",
    img: linkedin,
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 35mins ago",
    link: "https://ng.indeed.com/jobs?q=front%20end%20developer&from=searchOnHP&redirected=1&vjk=2ec2070de8976359",
  },
  {
    key: "1c",
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "https://www.metacareers.com/facebook-life/remote/?p[offices][0]=Remote%2C%20Canada&p[offices][1]=Remote%2C%20France&p[offices][2]=Remote%2C%20Germany&p[offices][3]=Remote%2C%20Ireland&p[offices][4]=Remote%2C%20Italy&p[offices][5]=Remote%2C%20Netherlands&p[offices][6]=Remote%2C%20Poland&p[offices][7]=Remote%2C%20Spain&p[offices][8]=Remote%2C%20Sweden&p[offices][9]=Remote%2C%20UK&p[offices][10]=Remote%2C%20US&offices[0]=Remote%2C%20Canada&offices[1]=Remote%2C%20France&offices[2]=Remote%2C%20Germany&offices[3]=Remote%2C%20Ireland&offices[4]=Remote%2C%20Italy&offices[5]=Remote%2C%20Netherlands&offices[6]=Remote%2C%20Poland&offices[7]=Remote%2C%20Spain&offices[8]=Remote%2C%20Sweden&offices[9]=Remote%2C%20UK&offices[10]=Remote%2C%20US&no_rdr=0",
  },
  {
    key: "1d",
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link: "https://boards.greenhouse.io/loominc/jobs/4010970005",
  },
  {
    key: "1b",
    img: linkedin,
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 35mins ago",
    link: "https://ng.indeed.com/jobs?q=front%20end%20developer&from=searchOnHP&redirected=1&vjk=2ec2070de8976359",
  },
  {
    key: "1c",
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "https://www.metacareers.com/facebook-life/remote/?p[offices][0]=Remote%2C%20Canada&p[offices][1]=Remote%2C%20France&p[offices][2]=Remote%2C%20Germany&p[offices][3]=Remote%2C%20Ireland&p[offices][4]=Remote%2C%20Italy&p[offices][5]=Remote%2C%20Netherlands&p[offices][6]=Remote%2C%20Poland&p[offices][7]=Remote%2C%20Spain&p[offices][8]=Remote%2C%20Sweden&p[offices][9]=Remote%2C%20UK&p[offices][10]=Remote%2C%20US&offices[0]=Remote%2C%20Canada&offices[1]=Remote%2C%20France&offices[2]=Remote%2C%20Germany&offices[3]=Remote%2C%20Ireland&offices[4]=Remote%2C%20Italy&offices[5]=Remote%2C%20Netherlands&offices[6]=Remote%2C%20Poland&offices[7]=Remote%2C%20Spain&offices[8]=Remote%2C%20Sweden&offices[9]=Remote%2C%20UK&offices[10]=Remote%2C%20US&no_rdr=0",
  },
  {
    key: "1d",
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link: "https://boards.greenhouse.io/loominc/jobs/4010970005",
  },
  {
    key: "1b",
    img: linkedin,
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 35mins ago",
    link: "https://ng.indeed.com/jobs?q=front%20end%20developer&from=searchOnHP&redirected=1&vjk=2ec2070de8976359",
  },
  {
    key: "1c",
    img: meta,
    post: "Product Manager",
    company: "Meta",
    location: "USA, Remote",
    type: "Full-time",
    pay: "120k-130k",
    timePosted: "posted 5mins ago",
    link: "https://www.metacareers.com/facebook-life/remote/?p[offices][0]=Remote%2C%20Canada&p[offices][1]=Remote%2C%20France&p[offices][2]=Remote%2C%20Germany&p[offices][3]=Remote%2C%20Ireland&p[offices][4]=Remote%2C%20Italy&p[offices][5]=Remote%2C%20Netherlands&p[offices][6]=Remote%2C%20Poland&p[offices][7]=Remote%2C%20Spain&p[offices][8]=Remote%2C%20Sweden&p[offices][9]=Remote%2C%20UK&p[offices][10]=Remote%2C%20US&offices[0]=Remote%2C%20Canada&offices[1]=Remote%2C%20France&offices[2]=Remote%2C%20Germany&offices[3]=Remote%2C%20Ireland&offices[4]=Remote%2C%20Italy&offices[5]=Remote%2C%20Netherlands&offices[6]=Remote%2C%20Poland&offices[7]=Remote%2C%20Spain&offices[8]=Remote%2C%20Sweden&offices[9]=Remote%2C%20UK&offices[10]=Remote%2C%20US&no_rdr=0",
  },
  {
    key: "1d",
    img: starry,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "130k-150k",
    timePosted: "posted 35mins ago",
    link: "https://boards.greenhouse.io/loominc/jobs/4010970005",
  },
  {
    key: "1e",
    img: linkedin,
    post: "Data Analytics",
    company: "Loom Inc",
    location: "Australia",
    type: "Full-time",
    pay: "105k-130k",
    timePosted: "posted 35mins ago",
    link: "https://boards.greenhouse.io/loominc/jobs/4010970005",
  },
  {
    key: "1f",
    img: linkedin,
    post: "Backend Engineer",
    company: "Facebook Inc",
    location: "USA",
    type: "Part-time",
    pay: "105k-110k",
    timePosted: "posted 35mins ago",
    link: "https://ng.indeed.com/jobs?q=front%20end%20developer&from=searchOnHP&redirected=1&vjk=2ec2070de8976359",
  },
];

export default jobArray;
